### ISSUE TITLE
out of range exception

### ISSUE THREAD

**Issue by JeffChilders** [barraudf/Unity-RandomDungeonGenerator#1]
if (cell[r + p[0]][c + p[1]] == CORRIDOR)
r = 1
p[0] = -2

**Comment by barraudf** [comment]
Hey,

I haven't touch this for a while, any details maybe? Do you have modified some code?

**Comment by JeffChilders** [comment]
I pulled the 2 classes DungeonOptions & Dungeon and put them in a console app. Initialized DungeonOptions and passed it to dungeon. Ran the code. the line of code is in check_tunnel().

**Comment by dandole** [comment]
### dungeon.cs 
this line of code in **check_tunnel**
if (cell[r + p[0]][c + p[1]] == CORRIDOR)
should be
if (cell[r + p[0]][c + p[1]] **!=** CORRIDOR)

**Comment by barraudf** [comment]
@dandole thank you for pointing this out!

I made the change
